"""Compatibility façade. Director owns policy; Modeler owns execution."""

from director.build_contract import BUILD_MODULES as BUILD_MODULE_POLICY
from modeler.engine.build_contract import (
    BUILD_MODULES,
    BuildModule,
    RequiredInput,
    WorkbookWriter,
    complete_build_modules,
    prepare_complete_build,
    verify_complete_build,
    write_complete_build,
    SOURCE,
    CONDENSED,
    DUPONT,
    JUDGMENT,
    OWNERSHIP,
    NORMALIZATION_JUDGMENT,
    NORMALIZATION,
    QUALITY,
    WORKING_CAPITAL,
    PER_SHARE,
    GEOGRAPHIC,
    OPERATING_KPI,
    COMPARABLE_SALES,
    SALES_PER_SQUARE_FOOT,
    REVENUE_PER_STORE,
    REVENUE_DRIVER,
)

__all__ = [
    "BUILD_MODULES",
    "BUILD_MODULE_POLICY",
    "BuildModule",
    "RequiredInput",
    "WorkbookWriter",
    "complete_build_modules",
    "prepare_complete_build",
    "verify_complete_build",
    "write_complete_build",
    "SOURCE",
    "CONDENSED",
    "DUPONT",
    "JUDGMENT",
    "OWNERSHIP",
    "NORMALIZATION_JUDGMENT",
    "NORMALIZATION",
    "QUALITY",
    "WORKING_CAPITAL",
    "PER_SHARE",
    "GEOGRAPHIC",
    "OPERATING_KPI",
    "COMPARABLE_SALES",
    "SALES_PER_SQUARE_FOOT",
    "REVENUE_PER_STORE",
    "REVENUE_DRIVER",
]
