"""Compatibility façade. Delegates without calculations, judgments, or wording."""

from __future__ import annotations

from composer.research.style import (
    BLACK,
    CJK_FACE,
    CJK_FILES,
    FIGURE_DPI,
    FIGURE_SIZE,
    GRAY,
    LABEL_PT,
    LATIN_FACE,
    LATIN_FILES,
    LINE_SPACING,
    MIN_WORD_GAP_EM,
    PT,
    RELATED_PT,
    SEARCH_DIRS,
    SECTION_PT,
    SPACE_CODEPOINT,
    TITLE_PT,
    WHITE,
    ResearchStyle,
    ResolvedFonts,
    apply_research_style,
    finish_figure,
    new_figure,
    resolve_required_fonts,
    spaced,
)

__all__ = (
    "BLACK",
    "CJK_FACE",
    "CJK_FILES",
    "FIGURE_DPI",
    "FIGURE_SIZE",
    "GRAY",
    "LABEL_PT",
    "LATIN_FACE",
    "LATIN_FILES",
    "LINE_SPACING",
    "MIN_WORD_GAP_EM",
    "PT",
    "RELATED_PT",
    "SEARCH_DIRS",
    "SECTION_PT",
    "SPACE_CODEPOINT",
    "TITLE_PT",
    "WHITE",
    "ResearchStyle",
    "ResolvedFonts",
    "apply_research_style",
    "finish_figure",
    "new_figure",
    "resolve_required_fonts",
    "spaced",
)
