"""Compatibility façade. Implementation is split across Extractor, Modeler and Director."""

from director.ingestion.management_kpi_enrichment import (
    PAGE_RESOLUTION_NAME,
    enrich_management_working_copies,
)
from extractor.ingestion.management_kpi_enrichment import (
    FISCAL_CALENDAR_BASIS,
    CalendarYearEvidence,
    ComparisonWindowEvidence,
    MetricExclusionEvidence,
    SourceInspection,
    decode_filing_text,
    definition_features,
    field_supporting_passages,
    format_physical_page_mapping,
    inspect_source_pdf,
    normalize_filing_amounts,
    page_reference_from_printed,
    printed_pages_from_reference,
    resolve_physical_pages,
    validate_physical_page_binding,
    collect_calendar_corpus,
    collect_exclusion_corpus,
    extract_comparison_window,
    extract_spsf_prior_period_levels,
    _metric_exclusion_evidence,
    _metric_excludes_53rd_week,
)
from modeler.ingestion.management_kpi_enrichment import (
    CAUSE_ACCESS,
    CAUSE_AMBIGUITY,
    CAUSE_IMPLEMENTATION,
    CAUSE_SELECTION,
    CAUSE_SOURCE_ABSENCE,
    DEFINITION_DIFFERENT,
    DEFINITION_EQUIVALENT,
    DEFINITION_UNRESOLVED,
    assess_definition_equivalence,
    build_group_decisions,
    enrich_management_payload,
    _document_pages,
    _failure_record,
    _pair_failure_mapping,
    _supporting_dict,
)
